config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  root "site#index"

  get "/observations", to: "observations#index"
  resources :observations

  get "/observation_sessions/start", to: "observation_sessions#start"
  get "/observation_sessions/end", to: "observation_sessions#end"
  # get "/observation_sessions/:id", to: "observation_sessions#show"
  resources :observation_sessions

  get "/profile", to: "profile#index"
  resources :profile

  get "/high_scores", to: "high_scores#index"
#  get "/high_score", to: "high_scores#index"
#  get "/high-score", to: "high_scores#index"
#  get "/high-scores", to: "high_scores#index"
#  resources :high_scores
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/observation.rb
class Observation < ApplicationRecord
  has_many :observation_session_observations
  has_many :observation_sessions, through: :observation_session_observations

  validates :start, presence: true
  validates :end, presence: true

  VALID_VALUES = ['left', 'right']
  validates :value, inclusion: { in: VALID_VALUES }
end

app/models/observation_session.rb
class ObservationSession < ApplicationRecord
  belongs_to :user

  has_many :observation_session_observations
  has_many :observations, through: :observation_session_observations
end

app/models/observation_session_observation.rb
class ObservationSessionObservation < ApplicationRecord
  belongs_to :observation_session
  belongs_to :observation
end

app/models/user.rb
class User < ApplicationRecord
  has_many :observation_session

  before_create :generate_emoji_display_name

  private
    def generate_emoji_display_name
      name = ""
      path = Rails.root.join("app", "assets", "data", "emojis.json")
      e_list = JSON.parse(File.read(path))["emojis"]
      for i in 1..3 do
        name.concat(e_list.sample["html"])
      end
      self.display_name = name
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    unless session[:user_id]
      @user = User.create()
      session[:user_id] = @user.id
    else
      @user = User.find(session[:user_id])
    end
  end
end

app/controllers/high_scores_controller.rb
class HighScoresController < ApplicationController
  def index
    @scores = Hash.new
    @users = User.all()
    @users.each do |usr|
      @scores[usr.id] = Hash.new
      #session_ids = usr.observation_session_ids
      observations = Observation.joins(:observation_sessions).where(observation_sessions: User.find(usr.id).observation_session_ids)
      if observations.nil? or observations.count == 0
      #if session_ids.count == 0
        @scores[usr.id][:total] = 0
        @scores[usr.id][:score] = 0
        @scores[usr.id][:left] = 0
        @scores[usr.id][:right] = 0
        next
      end
      #observations = Observation.joins(:observation_sessions).where(observation_sessions: session_ids)
      @scores[usr.id][:total] = observations.count
      @scores[usr.id][:left] = observations.where(value: "left").count
      @scores[usr.id][:right] = observations.where(value: "right").count
      @scores[usr.id][:score] = @scores[usr.id][:left].to_f / @scores[usr.id][:total] * 100
    end

    @scores_sorted = @scores.sort_by{|k,v| v[:score]}.reverse
    @scores_sorted = @scores_sorted[0..9]
  end
end

app/controllers/observation_sessions_controller.rb
class ObservationSessionsController < ApplicationController
  def show
    @observation_session = ObservationSession.find(params[:id])
  end

  def start
    @now = DateTime.now
    @user = current_user()
    @ongoing_session = ObservationSession.find_by(user:@user, end:nil)
    unless @ongoing_session
      @observation_session = ObservationSession.create(start:@now, user:@user)
    else
      # There is already a session for this user!?!?
      @ongoing_session.update_attribute(:end, @now)
      redirect_to :observations  # need a toast for "something went wrong"
    end
  end

  def end
    @now = DateTime.now
    @user = User.find(session[:user_id])
    @ongoing_session = ObservationSession.find_by(user:@user, end:nil)
    unless @ongoing_session
      redirect_to :observations  # need a toast for "something went wrong"
    else
      @ongoing_session.update_attribute(:end, @now)
      redirect_to @ongoing_session
    end
  end
end

app/controllers/observations_controller.rb
class ObservationsController < ApplicationController
  def index
    @observations = Observation.all()
    @observations_without_humans = @observations.where.missing(:observation_sessions)
    @observations_with_humans = @observations.joins(:observation_sessions).distinct
  end

  skip_before_action :verify_authenticity_token
  def create
    @observation = Observation.create(observation_params)
    @ongoing_sessions = ObservationSession.where(end: nil)
    @ongoing_sessions.each do |session|
      puts("for each session:")
      p(session)
      session.observations.append(@observation)
      session.save
    end
  end

  private
    def observation_params
      params.require(:value, :start).permit(:end)
    end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
    unless session[:user_id]
      redirect_to root_path and return
    else
      @user = User.find(session[:user_id])
    end
    @observations = Observation.joins(:observation_sessions).where(observation_sessions: User.find(@user.id).observation_session_ids)
    #puts(@observations)
    @sessions = ObservationSession.where(user:@user.id)
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    unless session[:user_id]
      @user = User.create()
      session[:user_id] = @user.id
    else
      @user = User.find(session[:user_id])
    end
    @randEmoji = random_emoji
  end

  def random_emoji
    name = ""
    path = Rails.root.join("app", "assets", "data", "emojis.json")
    e_list = JSON.parse(File.read(path))["emojis"]
    for i in 1..3 do
      name.concat(e_list.sample["html"])
    end
    name.html_safe
  end

end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/high_scores_helper.rb
module HighScoresHelper
end

app/helpers/observation_sessions_helper.rb
module ObservationSessionsHelper
end

app/helpers/observations_helper.rb
module ObservationsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/high_scores/index.html.erb
<a href="<%= root_path %>" class="underline text-orange-500">Home</a>
<h2 class="text-xl font-bold leading-tight mt-18 text-indigo-500">Top 10</h2>
<ol>
  <% @scores_sorted.each do |player| %>
    <li>
      (<%= player[0] %>) <%= @users.find(id=player[0]).display_name.html_safe %> : <%= player[1][:score] %> <small>(<span class="left-score"><%= player[1][:left] %></span><span class="right-score"><%= player[1][:right] %></span>)</small>
    </li>
  <% end %>
</ol>

<h2 class="text-xl font-bold leading-tight mt-18 text-indigo-500">All</h2>
<ol>
  <% @users.each do |player| %>
    <li>
      (<%= player.id %>) <%= player.display_name.html_safe %> : <%= @scores[player.id][:score] %> <small>(<%= @scores[player.id][:left] %> / <%= @scores[player.id][:right] %>)</small>
    </li>
  <% end %>
</ol>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nudge project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= yield :head %>
  </head>

  <body class="font-sans leading-normal tracking-normal">
    <main class="container bg-gray-200 mx-auto mt-20 px-40 py-10">
      <%= yield %>
    </main>
  </body>
</html>

app/views/observation_sessions/new.html.erb
<% content_for :head do %>
  <%= javascript_import_module_tag "observation_session" %>
<% end %>

<h2 class="text-2xl font-bold leading-tight my-4 text-indigo-500">Observation session START</h2>
<p>Hello user <%= @user.id %></p>
<div>Here should be a video feed</div>
<div>...and maybe a countdown?</div>
<button class="rounded bg-orange-500 hover:bg-orange-600 text-gray-100 font-bold my-5 py-2 px-4"><a href="<%= observation_sessions_end_path %>">End session</a></button>

app/views/observation_sessions/show.html.erb
<a href="<%= root_path %>" class="underline font-orange-500">Home</a>
<h2 class="text-2xl font-bold leading-tight my-4 text-indigo-500">Statistics for you observation session with id <%= @observation_session.id %></h2>
<p>Number of events observed: <%= @observation_session.observations.count %></p>
<p>Number of events going left: <%= @observation_session.observations.where(value:"left").count %> </p>
<p>Number of events going right: <%= @observation_session.observations.where(value:"right").count %> </p>

<div class="my-10">
  <a href="<%= observation_sessions_start_path %>"><button class="rounded bg-orange-500 hover:bg-orange-600 text-gray-100 font-bold py-2 px-4">Start a new session</button></a>
</div>

app/views/observation_sessions/start.html.erb
<% content_for :head do %>
  <%= javascript_import_module_tag "observation_session" %>
<% end %>

<h2 class="text-2xl font-bold leading-tight my-4 text-indigo-500">Observation session START</h2>
<div class="on-top-of-video">
  <p>Hello user <%= @user.id %>.</p>
  <p>Session ends in <span id="observation-session-countdown"></span></p>
  <p>Nudge the ball with your mind to make it go <strong>LEFT</strong>!</p>
</div>
<div class="container mx-auto py-5 h-96">
  <div class="session-video-stream bg-gray-100 object-center h-full w-3/4">Here should be a video feed</div>
</div>
<a href="<%= observation_sessions_end_path %>"><button id="end-session-button" class="rounded bg-orange-500 hover:bg-orange-600 text-gray-100 font-bold my-5 py-2 px-4">End session</button></a>

app/views/observations/index.html.erb
<a href="<%= root_path %>" class="underline text-orange-500">Home</a>
<h2 class="text-2xl font-bold leading-tight my-4 text-indigo-500">Overall statistics</h2>

<div class="my-5">
  <p><strong>Total number of events:</strong> <%= @observations.count %></p>
  <p><strong>Events left:</strong> <%= @observations.where(value:'left').count %>
  <strong>Events right:</strong> <%= @observations.where(value:'right').count %></p>
</div>

<div class="my-5">
  <p><strong>Number of events observed by humans:</strong> <%= @observations_with_humans.count %></p>
  <p><strong>Events left:</strong> <%= @observations_with_humans.where(value:'left').count %>
  <strong>Events right:</strong> <%= @observations_with_humans.where(value:'right').count %></p>
</div>

<h2 class="text-xl font-bold leading-tight mt-18 text-indigo-500">All observations</h2>
<ol>
  <% @observations.each do |obs| %>
    <li>
      <%= obs.end %>: <%= obs.value %>
    </li>
  <% end %>
</ol>

app/views/site/index.html.erb
<h1 class="text-5xl font-bold leading-tight my-4 text-indigo-500">Nudge project</h1>
<div>
  <p>Welcome, your generated name is (@user.id <%= @user.id %>):</p>
  <p class="text-5xl"><%= @user.display_name.html_safe %>
  <p>Here is a random emojistring for you: <%= @randEmoji %></p>
</div>
<a href="<%= observations_path %>" class="text-orange-500 underline">View your statistics</a>

<div class="my-10">
  <a href="<%= observation_sessions_start_path %>"><button class="rounded bg-orange-500 hover:bg-orange-600 text-gray-100 font-bold py-2 px-4">Start a new session</button></a>
</div>